---
# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: deploy EasyBuild documentation (only on push to main branch)
on:  # yamllint disable-line rule:truthy
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: checkout easybuild framework
        uses: actions/checkout@v3
        with:
          repository: easybuilders/easybuild-framework
          path: src

      - name: install mkdocs
        run: |
            pip install -r requirements.txt
            mkdocs --version

      - name: build tutorial
        # can't use --strict due to warnings being produced by mkdocs-redirect plugin
        # because we are re-directing .html pages
        # run: mkdocs build --strict && mkdocs gh-deploy --force
        run: mkdocs build && mkdocs gh-deploy --force
