---
# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: MarkDown linting
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: MarkdownLint mdl Action
        uses: actionshub/markdownlint@v2.1.2
        with:
          filesToIgnoreRegex: "(docs\\/demos\\/.*)"
