---
# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: test building of EasyBuild documentation
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Check out branfosj/easybuild-framework
        uses: actions/checkout@v3
        with:
          repository: branfosj/easybuild-framework
          ref: doc

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Codespell action
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: atleast,ninjs,simpy,proovread,namd,precice

      - name: check internal links
        run: |
          python ./.github/workflows/link_check.py

      - name: install mkdocs
        run: |
          pip install -r requirements.txt
          mkdocs --version

      - name: install branfosj/easybuild-framework
        run: (cd ../easybuild-framework && pip install -e .)

      - name: build tutorial
        # can't use --strict due to warnings being produced by mkdocs-redirect plugin
        # because we are re-directing .html pages
        # run: mkdocs build --strict
        run: mkdocs build
